version: "3.7"

services:
  fastapi-api:
    build: ./api
    container_name: fastapi-api
    ports:
      - "8000:8000"

  streamlit-app:
    build: ./app
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi-api
